spring:
  application:
    name: hei-std-grade

  datasource:
    url: ${DB_URL:}
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    locations:
      - classpath:db/migration

jwt:
  secret: ${JWT_SECRET:change-this-minimal-dev-secret-key-32bytes-min}
  expiration-ms: 3600000

aws:
  eventBridge:
    bus: ${AWS_EVENT_BRIDGE_BUS}